### ISSUE TITLE
Get list node available versions in machine

### ISSUE THREAD

**Issue by lowkorn** [clozed2u/gonvm#1]
Hi thank you for amazing tool I'm pretty love this but I need gonvm to get list available node version on machine.

example command
```
gonvm list
```
result
```
node/8.9.0
node/10.16.0
node/12.18.3
```

Hope you consider for this feature, thank you.

**Comment by bylatt** [comment]
I think only the installed version number should be fine, no need for `node/`.

**Comment by bylatt** [comment]
Add in #4
